haproxy_frontends:
  - name: apiserver
    bind_address: "*"
    bind_port: 64443
    mode: tcp
    default_backend: apiserver
    options:
      - tcplog
haproxy_backends:
  - name: apiserver
    mode: tcp
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers:
      - name: controlplane01
        address: controlplane01.dev.ryezone.com
        port: 6443
      - name: controlplane02
        address: controlplane02.dev.ryezone.com
        port: 6443
      - name: controlplane03
        address: controlplane03.dev.ryezone.com
        port: 6443
